[[Metatensor]]
arch = "aarch64"
git-tree-sha1 = "b34e1981008a54d378865ebf5b77bac72c6c266d"
os = "macos"

    [[Metatensor.download]]
    sha256 = "31ee94644d71a296d09f183d0830fcda0dbc17c9bf474dcbc3df8d7276dff730"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.aarch64-apple-darwin.tar.gz"
[[Metatensor]]
arch = "aarch64"
git-tree-sha1 = "274c50a726f6659a2cbbfec5291b5aad28c51fd0"
libc = "glibc"
os = "linux"

    [[Metatensor.download]]
    sha256 = "b55355ea6166d819d510c0b396e2958f7f255777e9e2c0385835880c8ef62780"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.aarch64-linux-gnu.tar.gz"
[[Metatensor]]
arch = "aarch64"
git-tree-sha1 = "8aea49512dd55b44d5e2d8b047954ccf44aef1cc"
libc = "musl"
os = "linux"

    [[Metatensor.download]]
    sha256 = "cc062b058c65f2ca26c723b203dbb2f4c9d25e7e003a0ec0817b52905e91e5bc"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.aarch64-linux-musl.tar.gz"
[[Metatensor]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "deed3974830f7553df3b207f4ea1c3fd3e78a4ea"
libc = "glibc"
os = "linux"

    [[Metatensor.download]]
    sha256 = "632692e6922620d595412395345373b6ee56ad535037b95428107692d66f7f04"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.armv6l-linux-gnueabihf.tar.gz"
[[Metatensor]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "376b7f0cddf6b2949a47c18d20b309630a2e87e5"
libc = "musl"
os = "linux"

    [[Metatensor.download]]
    sha256 = "ae66b0fac9dfa5978c2767349519877761c4e6b78c2cfda2caba471ced3c2ec7"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.armv6l-linux-musleabihf.tar.gz"
[[Metatensor]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3c67183f54a238c283be2d10abdce546b6b75acc"
libc = "glibc"
os = "linux"

    [[Metatensor.download]]
    sha256 = "d5a5d7841499ee58c59be1b3d2267234f7045c3d277cc7c7e53ea4c01bd96ab3"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.armv7l-linux-gnueabihf.tar.gz"
[[Metatensor]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "659299500e949a0612dc9d71f087826618d13419"
libc = "musl"
os = "linux"

    [[Metatensor.download]]
    sha256 = "4bcbb03251ebb31d7d178d51aeda68926f0e7854b00cebc453aadbb826fbbbcf"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.armv7l-linux-musleabihf.tar.gz"
[[Metatensor]]
arch = "i686"
git-tree-sha1 = "361086b4c2a2780b73f45847defabf0a52314e27"
libc = "glibc"
os = "linux"

    [[Metatensor.download]]
    sha256 = "8709282720a627c0b497f5564398c5265c30fc7e0b4ea80641d77bc0024d87c1"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.i686-linux-gnu.tar.gz"
[[Metatensor]]
arch = "i686"
git-tree-sha1 = "bb00f0a30fa0770c787de3618f42e50a6a4722b2"
libc = "musl"
os = "linux"

    [[Metatensor.download]]
    sha256 = "4609f0125961a096024d3f89ef07fdd788ae1821c18a688d84f08bdc843c9081"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.i686-linux-musl.tar.gz"
[[Metatensor]]
arch = "powerpc64le"
git-tree-sha1 = "4f2efa63659da672d4a0a7fef6d6be20f6b1af85"
libc = "glibc"
os = "linux"

    [[Metatensor.download]]
    sha256 = "a79b1966925c7fbd2df2e3fc6401b50c0c3f7da941ed0259a9826eef1003a1f9"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.powerpc64le-linux-gnu.tar.gz"
[[Metatensor]]
arch = "x86_64"
git-tree-sha1 = "13cac7f93ff18730304b1e416aab5ac5afc68fdd"
os = "macos"

    [[Metatensor.download]]
    sha256 = "3cd125bf679f20d9a98a194b3a35457d5406fd100b213d700034e272a6a9f441"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.x86_64-apple-darwin.tar.gz"
[[Metatensor]]
arch = "x86_64"
git-tree-sha1 = "59c3f52ee3931ba7d0653925d566096a8dc2c62f"
libc = "glibc"
os = "linux"

    [[Metatensor.download]]
    sha256 = "a9d07308165ac4d3e0ff0ecc2de9b39e48e9b6cd05b3bed81afe78505ba085fd"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.x86_64-linux-gnu.tar.gz"
[[Metatensor]]
arch = "x86_64"
git-tree-sha1 = "ed1b19e3d4c9ef4295a609a1423731972fd7184d"
libc = "musl"
os = "linux"

    [[Metatensor.download]]
    sha256 = "08aff643c5418584a239de38956f3e41b1eb35160d245ddd0e7291a2bdcb3061"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.x86_64-linux-musl.tar.gz"
[[Metatensor]]
arch = "x86_64"
git-tree-sha1 = "053e8f45f3c223e4311164304fc16929cd9fac09"
os = "freebsd"

    [[Metatensor.download]]
    sha256 = "7353d6aed574bab77b2fa823be958c47fe5d5a3c36883abcb3d3b29cab02edad"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.x86_64-unknown-freebsd.tar.gz"
[[Metatensor]]
arch = "x86_64"
git-tree-sha1 = "34697a613abc3a8181b1a78cecbf0de6b6117d48"
os = "windows"

    [[Metatensor.download]]
    sha256 = "b9284619658964ca20fc8f79aa324169008484c094810922159c36d9eda7be60"
    url = "https://github.com/Luthaf/Metatensor_jll.jl/releases/download/Metatensor-v0.1.17+0/Metatensor.v0.1.17.x86_64-w64-mingw32.tar.gz"
